[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eari-demosaic"
version = "0.1.2"
description = "EARI image demosaicking implementation"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "scipy>=1.17.1"
]
